site_name: osm-merge
site_description: Merge features and tags into existing OSM data.
# strict: true
site_url: "https://www.hotosm.org"

repo_name: "hotosm/osm-merge"
repo_url: "https://github.com/hotosm/osm-merge/"
edit_uri: "edit/main/docs/"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/hotosm/"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/hotosm"
    - icon: "fontawesome/solid/globe"
      link: "https://www.hotosm.org"
  copyright: Copyright &copy; 2010 HOTOSM
  generator: false

theme:
  name: material
  palette:
    primary: custom
  favicon: images/favicon.png
  logo: images/hot_logo.png
  # custom_dir: docs/overrides

extra_css:
  - css/extra.css

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.emoji:
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - git-revision-date-localized
  - exclude:
      glob:
        - plugins/*
        - __pycache__/*
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true

nav:
  - Home: index.md
  - Get Started:
      - About: about.md
      - License: LICENSE.md
      - Changelog: CHANGELOG.md
      - Code of Conduct: https://docs.hotosm.org/code-of-conduct
      - Versioning: https://docs.hotosm.org/dev-guide/repo-management/version-control/#creating-releases
  - Data Flow: dataflow.md
  - Conflation Guides:
      - General: conflation.md
      - ODK: odkconflation.md
      - Highways: highways.md
      - Calculations: calculations.md
      - Validating: validating.md
      - Boundaries: boundaries.md
  - Utilities:
      - Utilities: utilities.md
      - OSM Merge: osm-merge.md
      - TM Splitter: tm-splitter.md
      - Basemapper: basemapper.md
      - Odk2osm: odk2osm.md
      - Osm2favorites: osm2favorites.md
  - Data Conversion:
      - Data Formats: formats.md
      - MVUM: mvum.md
      - Trails: trails.md
      - OSM Highways: osmhighways.md
  - API:
      - basemapper: api/basemapper.md
      - convert: api/convert.md
      - conflator: api/conflator.md
      - sqlite: api/sqlite.md
      - osmfile: api/osmfile.md
      - yamlfile: api/yamlfile.md
      - filter_data: api/filter_data.md
      - odk2osm: api/odk2osm.md
      - parsers: api/parsers.md
