//
// Copyright (c) 2025 OpenStreetMap US
//
//     This is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//
//     This project is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//
//     You should have received a copy of the GNU General Public License
//     along with Underpass.  If not, see <https://www.gnu.org/licenses/>.
//

#ifndef __DATASTORE_HH_
#define __DATASTORE_HH_

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
#include "osmconfig.h"
#endif

#include <fstream>
#include <map>
#include <cstdio>
#include <filesystem>
#include <boost/format.hpp>
#include <boost/json.hpp>
// using namespace boost::json;
#include <sqlite3.h>
#include "osmobjects.hh"
using namespace osmobjects;

namespace datastore {

  class DataStore {
  private:
    void openOutfiles(const std::string &format);
  protected:
    sqlite3 *db;
    multipolygon_t aoi;
    std::map<long int, OsmNode> node_cache;
    std::map<long int, std::shared_ptr<OsmWay>> way_cache;
    std::map<long int, OsmRelation> relation_cache;
    /// The project boundary
    // std::map<long int, std::shared_ptr<OsmWay>> aoi;
    // FIXME: this should probably be a vector of tag/value pairs, but
    // keep it simple for now.
    std::vector<std::string> keywords;
    std::string suffix;
    struct outfiles {
      FILE *file;
      polygon_t boundary;
    };
    std::vector<outfiles> output;
    bool cache_files;
  public:
    bool setupNodeCache(const std::string &dbname);
    /// Features only need to be cached if the data is wanted, otherwise
    /// it's disabled for tag filtering and clipping.

    std::shared_ptr<const OsmNode> getNode(long int id);

    DataStore(void) {
      cache_files = false;
      suffix = "osm";
      sqlite3_open("node_cache.db", &db);
      // If verbose debug logging is enabled, these don't do anything.
      sqlite3_trace_v2(db, 0, nullptr, nullptr); // Disable tracing￼
      auto rc = sqlite3_config(SQLITE_CONFIG_LOG, NULL, NULL);
    }

    ~DataStore(void) {
      sqlite3_close(db);
      if (suffix == "osm") {
        // OSM XML needs to close the entry
        std::string header = "</osm>\n";
        for (auto [task, poly] : output) {
          std::fwrite(header.c_str(), 1, header.size(), task);
        }
      }
    }
    /// Set the keyword for tag filtering
    void addSuffix(const std::string &value) {
      suffix = value;
    }
    /// Set the keyword for tag filtering
    void addTagFilter(const std::string &tag) {
      keywords.push_back(tag);
    }
    std::map<long int, OsmNode>getNodes(void) {
      return node_cache;
    }
    std::map<long int, std::shared_ptr<OsmWay>>getWays(void) {
      return way_cache;
    }
    std::map<long int, OsmRelation>getRelations(void) {
      return relation_cache;
    }
    /// Add an AOI for clipping data
    void addAOI(const multipolygon_t &aoi);
    void tagFilter(const std::string &outfile, const OsmWay &way);
    void writeCache(const std::string &outfile);
    void writeFeature(const OsmWay &way);
    void writeFeature(const OsmNode &node);
  };
} // end of datastore namespace

#endif  // end of __DATASTORE_HH_

// Local Variables:
// mode: C++
// indent-tabs-mode: nil
// End:
