//
// Copyright (c) 2025 OpenStreetMap US
//
//     This is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//
//     This project is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//
//     You should have received a copy of the GNU General Public License
//     along with Underpass.  If not, see <https://www.gnu.org/licenses/>.
//

#ifndef __GEOSJON_HH_
#define __GEOJSON_HH_

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
#include "osmconfig.h"
#endif

#include "osmobjects.hh"
using namespace osmobjects;

namespace geojson {

class GeoJson {
private:
    
public:
    std::string &createGeoJson(OsmNode) const;
    std::string &createGeoJson(OsmWay) const;
    std::string &createGeoJson(OsmRelation) const;
};

} // end of geojson namespace
#endif  // end of __GEOJSON_HH_ 

// Local Variables:
// mode: C++
// indent-tabs-mode: nil
// End:
