//
// Copyright (c) 2025 OpenStreetMap US
//
//     This is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//
//     Underpass is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//
//     You should have received a copy of the GNU General Public License
//     along with Underpass.  If not, see <https://www.gnu.org/licenses/>.
//

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
#include "osmconfig.h"
#endif

#include <boost/log/trivial.hpp>

#include "osmobjects.hh"
using namespace osmobjects;
#include "geojson.hh"

namespace geojson {

std::string &
GeoJson::createGeoJson(OsmNode node) const
{
    BOOST_LOG_TRIVIAL(debug) << "GeoJson::createGeoJson(OsmNode) called";
}

std::string &
GeoJson::createGeoJson(OsmWay way) const
{
    BOOST_LOG_TRIVIAL(debug) << "GeoJson::createGeoJson(OsmWay) called";
}

std::string &
GeoJson::createGeoJson(OsmRelation relation) const
{
    BOOST_LOG_TRIVIAL(debug) << "GeoJson::createGeoJson(OsmRelation) called";
}

} // end of geojson namespace

// Local Variables:
// mode: C++
// indent-tabs-mode: nil
// End:
