//
// Copyright (c) 2025 OpenStreetMap US
//
//     This is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//
//     Underpass is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//
//     You should have received a copy of the GNU General Public License
//     along with Underpass.  If not, see <https://www.gnu.org/licenses/>.
//

// This is generated by autoconf
#ifdef HAVE_CONFIG_H
#include "osmconfig.h"
#endif

#include <boost/log/trivial.hpp>

#include "osmobjects.hh"
using namespace osmobjects;
#include "osmpbf.hh"

// namespace osmpbf {

void
PBF_Parser::node_callback(uint64_t osmi,
                          double lon,
                          double lat,
                          const Tags &tags)
{
    BOOST_LOG_TRIVIAL(debug) << "PBF_Parser::node_callback() called";
}

void
PBF_Parser::way_callback(uint64_t osmid,
                         const Tags &tags,
                         const std::vector<uint64_t> &refs)
{
    BOOST_LOG_TRIVIAL(debug) << "PBF_Parser::way_callback() called";
}

void
PBF_Parser::relation_callback(uint64_t osmid,
                              const Tags &tags,
                              const References &refs)
{
    BOOST_LOG_TRIVIAL(debug) << "PBF_Parser::relation_callback() called";
}

//} //  end of osmpbf namespace

// Local Variables:
// mode: C++
// indent-tabs-mode: nil
// End:
